version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=config.docker_config
      - PYTHONPATH=/
    build: .
    command: python pytition/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
